server.port=8761

spring.application.name=eureka-server

# IMPORTANT: Eureka server must NOT register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Bind correctly inside Kubernetes
eureka.instance.hostname=eureka-server
eureka.instance.prefer-ip-address=false

# Prevent startup race issues
eureka.server.wait-time-in-ms-when-sync-empty=0